### ISSUE TITLE
"sorry, too many clients already" will cause rollback 

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#1056]
ErrorPolicyUnhandledApplicationException libpq: failed (FATAL:  sorry, too many clients already

cause rollback 

instead of simply waiting for the connection to be released, rollback occurs illogically.

v12

**Comment by erikd** [comment]
The rollback occurs because of the `libpq` exception and because `db-sync` has volatile data that gets can get lost if there is no rollback. We want to re-engineer the lower level libraries so that `db-sync` will not need to maintain its own copy of ledger state (likely to take at least 3 months). However, once that happens, there will be no more volatile data and any `libpq` exception will lead to at most, rolling back 2 or 3 blocks instead of thousands.

The fact that `libpq` threw an exception is a PostgreSQL tuning issue, not a `db-sync` issue. I am far from PostgreSQL tuning expert but I would suggest starting with  https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server .

**Comment by mgajda** [comment]
What is worse, is that "sorry, too many clients already" indicates leaking of connections.

Any idea of how to avoid CardanoDBSync from leaking 100 connections?
Is it good idea to just terminate it once a week?

**Comment by erikd** [comment]
I was the only dev in `db-sync` in the beginning and have always had at least one instance running. I have never seen this issue and I have run `db-sync` un-interrupted (admittedly with a very low number of connections) for weeks on end.

> Is it good idea to just terminate it once a week?

I have never seen a need to but if you do, please go ahead.

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
