### ISSUE TITLE
Determining order of transaction inputs

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#106]
[TxIn](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L93) is missing an `index` property, so it's currently not possible to determine the sort order of the transaction inputs set. The property is [present in TxOut](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L86-L88).

**Comment by erikd** [comment]
@ksaric We should add the index like:
```
  TxIn
    txInId              TxId                -- The transaction where this is used as an input.
    txIndex             Word16              -- Index within the Tx
    txOutId             TxId                -- The transaction where this was created as an output.
    txOutIndex          Word16              sqltype=txindex
    UniqueTxin          txOutId txOutIndex
```
and just add this as a migration. No need to squash this.

**Comment by dcoutts** [comment]
@rhyslbw can you explain why you need this? Yes outputs are indexed because other transactions need to refer to them. This is not the case for inputs.

If you can avoid relying on an order for Byron inputs, that would be good since it will make the transition with Shelley simpler. In Shelley, transaction inputs are a set, so _there is no order_.

If we do add this, it'll make life harder for Shelley, since it would have to become optional. Much simpler to never rely on input order at all.

**Comment by rhyslbw** [comment]
@dcoutts Thanks for the notification. Applying the Shelley model now makes a lot of sense, as this was simply a matter of looking for consistency in an API when sorting `inputs` and `outputs` for display
