### ISSUE TITLE
Missing datum values?

### ISSUE THREAD

**Issue by jesuspc** [input-output-hk/cardano-db-sync#1076]
**OS**
Your OS: NixOS 21.05

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 12.0.1
PostgreSQL version: 11.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker image (inputoutput/cardano-db-sync:12.0.1)

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
I am wondering if this is a bug or expected behaviour.

**Problem Report**

From time to time I encounter transactions which contain UTXOs associated to script addresses with datum hashes for which no corresponding entries are available in the datum table of a fully-synched DB.

Here is a randomly selected example:

```
select data_hash from tx_out where tx_id = (select id from tx where hash = '\xfc6536534b03f818494f21698994d387c879a121b263153a06975d056d9cf13e');
```

This will output `\x4a664c584e552af70dcc255921811b5f62637fd781a43e5c289d9e571a227117`. Then:

```
select * from datum where hash = '\x4a664c584e552af70dcc255921811b5f62637fd781a43e5c289d9e571a227117';
```

finds 0 rows.

As [datums values are included in the witness set of the corresponding transactions](https://cardano.stackexchange.com/questions/4902/how-do-i-read-the-datum-of-an-output) I would expect all hashes to have a matching entry in the datum table.

**Comment by sorki** [comment]
I think this is expected since a locking transaction uses only a datum hash, which is later revealed when you try to spend the locked utxo. Locking transaction only uses datum hash, to spend utxo locked at script address you need to provide full datum and redeemer (which is then compared to datum hash used in locking tx) and a script itself.

So until there's a spending transaction you won't be able to query full datum.

**Comment by kderme** [comment]
Datum values are included in the witness set of the transaction that unlocks the output, not the one that creates the output. So it's possible to have a datum hash in an output before its value ever appeared on chain. db-sync collects datum values only from the chain and doesn't use any off-chain source (if there is any), that's why it's missing.

**Comment by kderme** [comment]
I should note though, calling this table `datum` is a misnomer that stayed and may be causing confusion. This table also include redeemer plutus data, so it should be renamed to `plutus_data` or something.

**Comment by AngelCastilloB** [comment]
Also, note that datums values can also be in the witness set of the transaction that **creates** the output if the options  "**tx-out-datum-embed-file**" or "**tx-out-datum-embed-value**" are used when constructing the transaction that creates the eUTXO.
