### ISSUE TITLE
Delete operation is very slow for cleaning up small number of blocks (~2100)

### ISSUE THREAD

**Issue by markovivan** [input-output-hk/cardano-db-sync#1109]
**OS**
Your OS: WINDOWS 11

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):Cardano DB Sync 12.0.2
PostgreSQL version:11.5-alpine

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker image

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):Docker

**Additional context**
N/A

**Problem Report**
DB-SYNC needed to rollback/delete blocks. Log message: 
[db-sync-node:Info:455] [2022-05-03 13:51:47.35 UTC] Rolling back to slot 59938903, hash 2d417e88ca07ab923885ed807223a7a5ceaab13e07648dd7d8e5880821029413
[db-sync-node.Subscription:Notice:47] [2022-05-03 13:51:47.35 UTC] Identity Required subscriptions started
[db-sync-node:Info:455] [2022-05-03 13:51:47.37 UTC] Deleting 2127 blocks up to slot 59982653
Connecting to network: mainnet

The process was taking 12+ hours, until I found a reference to a similar issue: https://github.com/input-output-hk/cardano-db-sync/issues/975, and created the suggested indexes. As a result the block deletetion was able to complete in less than 10 seconds.

Recommandation: These indexes should be included in the base image/build to improve the performance of the delete operation

**Comment by erikd** [comment]
The indices have already been added on the master branch. In addition, the database schema has changed so the indices in issue #975 are unlikely to be correct.

Is it worth doing a `12.0.3` release that just adds these indices?

**Comment by markovivan** [comment]
Not a release just for the indices, but it's definitely worth adding them
in the next scheduled release. They made a big difference in resolving
getting the node running vs waiting days for the blocks to delete.

**Comment by BisonDee** [comment]
A release to add these indices would be greatly appreciated

**Comment by markovivan** [comment]
Yes, thank you.

**Comment by grim-i-am** [comment]
the solution mentioned in https://github.com/input-output-hk/cardano-db-sync/issues/975 (creating missing indexes for foreign keys) fixed the issue for me for db-sync v12.* but now I have the same issue with v13 although the script in the above link does not find any missing indexes.

I upgraded my db sync to v13 but the schema updates failed because a new, unique index couldn't be created because of duplicate key constraints. That forced me to recreate the db and restore from the latest snapshot. My db-sync has been stuck on "Deleting 1259374 blocks up to slot 71452796" for almost 11 hours now. Very frustrating.

**Comment by kderme** [comment]
There shouldn't be any long rollback when you restore from a snaphot. Make sure you follow the instructions from the release https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.0.4.
