### ISSUE TITLE
Querying Total Value Locked

### ISSUE THREAD

**Issue by sgornostal** [input-output-hk/cardano-db-sync#1183]
Can someone help to figure out how to calculate TVL for the entire protocol?

**Comment by erikd** [comment]
I am the main dev for `cardano-db-sync`. I understand the basic general concept of total value locked is, but I do not think it is something that Cardano itself actually even has.

TVL, as I understand it, is usually about the amount of an asset locked in a lending platform. Cardano itself is not a lending platform. There may be a lending platform that accepts Cardano/ADA as collateral, but that is external to Cardano itself, and definitely not something that is recorded in `db-sync`.

Furthermore, staking ADA does not "lock" it. The way Cardano avoids locking due to staking in by staking rewards for epoch `N` being dependent on the balance at the end of epoch `N - 2` (an epoch in the Cardano protocol is 5 days).

Am I way off the mark here?

**Comment by erikd** [comment]
If you go to https://pool.pm/ you will see that currently about 72% of all ADA in circulation is staked.

**Comment by erikd** [comment]
I posted a link to this question in a TG group I am in and they suggested that " any ADA in script address is a part of TVL". Is that what you mean?

**Comment by erikd** [comment]
@sgornostal I need you feedback on what exactly you need.

**Comment by sgornostal** [comment]
Hi @erikd , sorry for delayed response,
I found this chart https://defillama.com/chain/Cardano?currency=ADA and there are other sites that are showing 251.8m ADA as Total Value Locked, and I'm wondering how they are getting that value

**Comment by erikd** [comment]
If you want to know how they (DeFiLlama) are getting that value, you should probably ask them.

**Comment by sgornostal** [comment]
ok, thanks, I'll ask them
I thought it is something general and I can be done by sum amount of particular tables
