### ISSUE TITLE
Cannot query UTxO

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-db-sync#1185]
**OS**
Your OS: macOS 12.4

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.0
PostgreSQL version: 14.4

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: 1.35.0

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
Cannot query the UTxO I want from `utxo_view`.

**Problem Report**

```sql
select * from utxo_view where address = 'addr1x9e7m0aevqn7cp3xdxfafppm7a8djvndw8p7a8lrvh7y8ztnaklmjcp8asrzv6vn6jzrha6wmyex6uwra607xe0ugwysnwdr7u';
```

```
 id | tx_id | index | address | address_raw | address_has_script | payment_cred | stake_address_id | value | data_hash | inline_datum_id | reference_script_id 
----+-------+-------+---------+-------------+--------------------+--------------+------------------+-------+-----------+-----------------+---------------------
(0 rows)
```

**Comment by erikd** [comment]
`utxo_view` was useful a couple of years ago, but since calculation of the calculation of the UTxO set is now so slow, its utility has drastically reduced.

As for your question, that query returns results for me:
```
# select count (*), sum (value) from utxo_view where address = 
    'addr1x9e7m0aevqn7cp3xdxfafppm7a8djvndw8p7a8lrvh7y8ztnaklmjcp8asrzv6vn6jzrha6wmyex6uwra607xe0ugwysnwdr7u';
 count |    sum     
-------+------------
  1700 | 5093815227
(1 row)
```
Is you `db-sync` instance fully synced? Check if using [this query](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md#sync-progress-of-db-sync).

**Comment by erikd** [comment]
@siegfried Can this be closed?

**Comment by siegfried** [comment]
Sorry, had troubles to test out. Since my machine is too slow for this. Let's close it for now.
