### ISSUE TITLE
DBSync 12 Mainnet Snapshots are missing

### ISSUE THREAD

**Issue by wutzebaer** [input-output-hk/cardano-db-sync#1213]
The URL from the release page 
https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#12/
has no snapshots, its empty at all

Or should i use v13 ? But since it states to be for Node 1.35, which is deprecated, i'm unsure what to use

**Comment by reqlez** [comment]
Well, the issue I think is that nobody assumed that 1.35.x would get pulled.

i'm running DB-sync 13.0.2 + cardano-node 1.35.2 on mainnet ( just for DB-SYNC purposes ) and it's fine. The reason version 1.35.x was pulled was because of an issue with block production where people would lose height battles in some cases. I don't see an issue with running 13.0.2 + 1.35.2 just for DB-SYNC purposes, personally.

**Comment by erikd** [comment]
Yes, `db-sync` can run with a relatively wide range of `node` versions. Although I haven't tested it, I am pretty sure the latest `db-sync` can run with any `node` version after `1.30.*` although obviously not all versions support the various hard forks.

**Comment by wutzebaer** [comment]
Ok so i assume 13 is fine, thank you! I'll run it with a 1.34.1 node
