### ISSUE TITLE
[Docs build failure]DB schema is `not found`

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/cardano-db-sync#1351]
**OS**
Web (GitHub)

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): `master` branch
PostgreSQL version: N/A

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: `hydra`

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): none

**Problem Report**
When clicking 'SQL DB Schema' in toplevel GitHub page, I get `not found` from Hydra page.
_Apologies for screenshot:_
![image](https://user-images.githubusercontent.com/685529/217106862-2b852429-8495-4a24-886c-47e862067bbf.png)

**Comment by kderme** [comment]
I can't recall what was this link about? The `Schema documentation` points to https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/schema.md and still works.

**Comment by mgajda** [comment]
Basically the issue is that links to automatically _generated_ documentation from CI are broken.

**Comment by ArturWieczorek** [comment]
@kderme This was pointing to hydra:

https://hydra.iohk.io/job/Cardano/cardano-db-sync/native.haskellPackages.cardano-db.checks.test-db.x86_64-linux/latest/download/1

and since Hydra is gone this is not available anymore.

@jbgi Do you know what is the status with Cicero CI - Could we have it pushed it (schema graphic) there or it is not ready yet ?

**Comment by kderme** [comment]
This link has been removed, since the schema can be found at `doc/schema.md`. Closing
