### ISSUE TITLE
Replace panic by exceptions

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1459]
This becomes possible after https://github.com/input-output-hk/cardano-db-sync/issues/1438. Before that, simple exceptions were caught by the mini-protocol subscriber and all the threads were restarted. Now an exception at any storage thread is enough to kill db-sync.

**Comment by Cmdv** [comment]
Could we discuss which route we are going to take with errors in general ? There seems to be a mishmash of different ways we do it through out this repo and it would be great if we could align into a single method (if possible).

@kderme @sgillespie what do you both think in regards to how we handle errors?

**Comment by Cmdv** [comment]
Ok I'm going to attempt to use https://github.com/fpco/safe-exceptions as it seems to be used in other project at IOG

**Comment by kderme** [comment]
I wasn't aware of the library, but do we need something more complicated than `Control.Exception` for this? The library is based around `MonadCatch`, `MonadMask` monads, that we don't use in db-sync. Actually from a quick search, more panics are in pure code, where a `error` may suffice.

**Comment by sgillespie** [comment]
> I wasn't aware of the library, but do we need something more complicated than Control.Exception for this? 

AFAIK `Control.Exception` does not have `MonadThrow` (also provided by `exceptions` package), which I think is easier when working with transformers. `exceptions` is also built on top of `Control.Exception`. If we're going for GHC runtime exceptions, I think it's worth looking at.

**Comment by Cmdv** [comment]
@kderme no I'm happy with `Control.Exception`, just trying to have a unified way of dealing with errors. 

Here are some of the various ways we do things:
`Control.Monad.Trans.Except.Exit (orDie)` 
`Control.Monad.Trans.Except.Extra (left, firstExceptT, hoistEither, handleIOExceptT)` 
`GHC.Base (error)`
`Control.Exception`
`throwIO e`
`panic`
`Either Text (..)`
`Either SyncNodeErrors ()`

Error types:
`SyncNodeErrors`
`FetchError`
`PoolOfflineFetchError`

Also lots of
`ExceptT SyncNodeError IO ()`

from reading [this blog post](https://www.fpcomplete.com/haskell/tutorial/exceptions/), it states:
> making large sum types containing all possible exceptions, and wrapping all your IO code in ExceptT, is a major anti-pattern. It has three major downsides:
It slows down your code.
It introduces confusion: your type signatures imply that it has only one way to fail (the explicit error case), but in reality runtime exceptions still exist.
It becomes much harder to use combinators like concurrently safely due to [monadic state](https://www.youtube.com/watch?v=KZIN9f9rI34).

Just thought as we're taking out `panic` why not make the way we handle exceptions the same. But if this is out of scope then I understand and will simply replace `panic` -> `error` 👍

**Comment by sgillespie** [comment]
> Could we discuss which route we are going to take with errors in general ? There seems to be a mishmash of different ways we do it through out this repo and it would be great if we could align into a single method (if possible).

The most common pattern I'm seeing lately is

 * Use EitherT/ExceptT for errors in pure code
 * Use GHC runtime exceptions in IO

Here's another approach from the [RIO documentation](https://github.com/commercialhaskell/rio#exceptions):

> If something can fail, and you want people to deal with that failure every time, then return a Maybe or Either value.
> If the user will usually not want to deal with it, then use exceptions. In the case of pure code, use a MonadThrow constraint. In
> the case of IO code: use runtime exceptions via throwIO.

**Comment by Cmdv** [comment]
@sgillespie cool I was looking at `RIO` as it was mentioned in the blog posts I've been reading. Though as my comment just previous to yours. One post mentions `ExceptT slows down your code` but unsure how so 🤔
