### ISSUE TITLE
Missing sanchonet `delegation_vote` table indexes

### ISSUE THREAD

**Issue by gabrielKerekes** [input-output-hk/cardano-db-sync#1531]
**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): sancho-2-0-0

**Problem Report**
There are currently no additional indexes on the `delegation_vote` table, there's only the primary key index. It would be useful to add indexes for some of the columns similar to the `delegation` table. In our case indexes for `addr_id`, `drep_hash_id` and `tx_id` might be useful in the future since we do queries based on these columns - right now the queries aren't slow but they'll slow down as the data grows ofc.

Indexes for the `delegation` table:
```SQL
"delegation_pkey" PRIMARY KEY, btree (id)
"idx_delegation_active_epoch_no" btree (active_epoch_no)
"idx_delegation_addr_id" btree (addr_id)
"idx_delegation_pool_hash_id" btree (pool_hash_id)
"idx_delegation_redeemer_id" btree (redeemer_id)
"idx_delegation_tx_id" btree (tx_id)
```

Indexes for the `delegation_vote` table:
```SQL
"delegation_vote_pkey" PRIMARY KEY, btree (id)
```

**Comment by kderme** [comment]
Hello @gabrielKerekes, indexes can be added by users in any table they like, as long as there are no name colision with existing indexes. Given the big number of tables and fields in db-sync it would be impossible to have indexes everywhere by default.

They can be added either manually, or you can add them at the schema [migration files](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/schema-management.md#schema-management). Indexes added in a stage-3 file will be executed at the begining of syncing, while indexes in a stage-4 when db-sync reaches the tip of the chain. This sometimes makes a different on big tables since creating an index at the end is usually faster than maintaining them during syncing.

**Comment by gabrielKerekes** [comment]
Ok, just to confirm: You don't plan on adding the indexes to the codebase, we should add them manually on our instances, correct?

**Comment by kderme** [comment]
Yes there is not such plan currently

**Comment by gabrielKerekes** [comment]
Ok, understood. We'll try to do that. Thank you!
