### ISSUE TITLE
Word64 values in Haskell schema are treated as Int64 in Persistent large values be displayed as negative

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#163]
SELECT * FROM pool WHERE hash='\xdc240e2e02c1ff7914a840749df10452b900531e43e99d7554e4a59d'

15	"binary data"	12345678000000	22733	14	0.1234	12345000000	424
37	"binary data"	1000000000000	22733	14	0.1234	12345000000	1044
327	"binary data"	-2537764290116403776	22733	14	0.9999	-2537764290116403776	50091

**Comment by erikd** [comment]
The problem here is that the ledger allows arbitrary (and nonsensical) values for the pledge amount (and fixedCost). Specifically that allow any `Word64` even if that value is greater than the current total supply.

Even `Word64` is problematic due to https://github.com/yesodweb/persistent/issues/1095

**Comment by erikd** [comment]
I have a potential fix for this but it I am waiting on some dependency and Nix/CI issues fixed before I can test my solution.

**Comment by erikd** [comment]
I have a fix for this on my `erikd/persistent-Word64` branch, but I would prefer not to merge that until I make further progress getting  yesodweb/persistent#1096 merged.
