### ISSUE TITLE
Add nullable slot_leader.pool_hash_id

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#195]
To enable a model of `Block.forgedBy` -> `StakePool` and `StakePool.blocksForged` -> `[Block]`
See https://github.com/input-output-hk/cardano-ledger-specs/pull/1637

**Comment by disassembler** [comment]
Doesn't this duplicate the slot_leader table?

**Comment by papacarp** [comment]
Yea, you can get to pool id through the slot_leaders table.  It would, however, be very convenient if we could have the pool id in the  slot leader table rather than part of the vkey.  I currently convert the vkey to a pool id as follows and store it in a new column in the slot leader table:
```
vkey = "5820"+p['hash'][2:]
h = hashlib.blake2b(digest_size=28)
h.update(binascii.unhexlify(p['hash'][2:]))
poolid = h.hexdigest()
```
This allows me to do a join and build out blocks per pool fairly easily.

**Comment by rhyslbw** [comment]
@disassembler Yes, it would. I've updated the title to extend the leaders table with a key for joining easily

@papacarp thanks for adding your workaround. Hopefully you can refactor away from this, as modifying schema of the tables managed by `cardano-db-sync` is advised against by @erikd

**Comment by rhyslbw** [comment]
Other columns needing the same relationship:
- https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L207
- https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L214
