### ISSUE TITLE
Feature request: Differentiate era a transaction was made

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-db-sync#211]
Byron-era transaction and Shelley-era transactions work differently and so it'd be great to have a row in the transaction saying which era the transaction was created in.

This would continue being useful in future hardforks also

**Comment by erikd** [comment]
The "era" of a transaction is really an aspect of the block rather than of the transaction, so any "era" field should go in the `block` table rather than the "tx` table.

However, even in the block table, there is already a way if distinguishing Byron vs Shelley blocks:
```
select * from block where vrf_key is not null ;
```
will only return Shelley blocks. 

Not saying that having a column for the era in the block table is not useful, just that it already indirectly exists.

**Comment by SebastienGllmt** [comment]
Perfectly, then we have exactly what we need
