### ISSUE TITLE
pgstat views dropped by db-sync on restart

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-db-sync#255]
We need some sort of white list on what does not get dropped when db-sync is restarted. We're working on adding pgstat views so we can analyze where slow queries are occurring and they can be optimized further.

**Comment by erikd** [comment]
In order for migrations to happen smoothly all `VIEW`s need to be dropped before migrations start and then be reloaded after migrations. Maintaining `VIEW`s across migrations is not possible because if I migration makes **any** change to a table that is used in a `VIEW` the migration will be aborted by Postgres.

The solution is to let the `VIEW` be deleted during migration (as happens now) and re-add the view at the end of the migration process as is done in https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-3-0001-20190816.sql .

**Comment by erikd** [comment]
SInce the view in question does not reference any parts of the `db-sync` schema, we can simply whitelist it.
