### ISSUE TITLE
Capture cardano-node version

### ISSUE THREAD

**Issue by bitnado-io** [input-output-hk/cardano-db-sync#303]
Would it be possible to have `cardano-db-sync` also store the release/version of the target `cardano-node` instance in postgres? E.g. currently the [latest release of `cardano-node` is `1.20.0`](https://github.com/input-output-hk/cardano-node/releases)

The version is accessible from `cardano-cli`:

```
bash-4.4# cardano-cli version
cardano-cli 1.20.0 - linux-x86_64 - ghc-8.6
```

But dynamically determining the version through postgres seems like a good fit for the `meta` table and would be useful

**Comment by erikd** [comment]
What happens when the node version is updated, but the protocol is still compatible? Should this be updated? Even if its downgraded? (eg `db-sync` is currently compatible with `node` `1.19.0`, `1.19.1` and `1.20.0`. Unfortunately the over-the-domain-socket version is not available.

There is another problem here, how is `db-sync` even supposed to know what version of `node` it is connecting to. It just connects to a local domain socket of a running node. There is not currently any local query that can be made of the node, that returns version information.

**Comment by bitnado-io** [comment]
> There is another problem here, how is db-sync even supposed to know what version of node it is connecting to. It just connects to a local domain socket of a running node. There is not currently any local query that can be made of the node, that returns version information.

thats unfortunate that it's not currently possible. appreciate the consideration. we can just figure out another workaround thanks!
