### ISSUE TITLE
cardano-db-sync-extended: epochs with 0 transactions not present in table

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#35]
See https://github.com/input-output-hk/cardano-graphql/issues/126 for a query result aimed at `testnet`

**Comment by erikd** [comment]
This issue turned up another problem with how old epochs are updated.

In the Classic consensus era old epochs could just be updated when an epoch boundary block is found.

In the OBFT era there are no epoch boundary blocks (EBB), so the epoch tabled cannot be updated on the EBB.

Instead I have taken to storing the last cached epoch and the slots per epoch values in separate `IORef`s. This allows these values to be accessed without using the database.
