### ISSUE TITLE
resource consumption spike when bootstrapping db-sync

### ISSUE THREAD

**Issue by bitnado-io** [input-output-hk/cardano-db-sync#455]
cardano-db-sync version: 7.1.0
cardano-node version: 1.24.2

this problem is currently preventing us from syncing db-sync. any insight would be greatly appreciated!

db-sync typically has a memory footprint of under 1 GB until reaching around August-November 2020 in the blockchain history when the bootstrap process suddenly utilizes over 2 GB of memory. this sudden spike makes it impossible to bootstrap on modest hardware.

why does that particular point of history require so much memory resources? are there any optimizations that could be made to db-sync that would normalize the resource consumption?

here’s some debug information collected at 2020-12-20T11:31:51.499Z:

tip reported by db-sync in postgres: 2020-08-27 09:05:00

db-sync logs:
```
[db-sync-node:Info:35] [2020-12-20 09:24:20.29 UTC] Starting chainSyncClient
[db-sync-node.Subscription:Notice:29] [2020-12-20 09:24:20.31 UTC] [String "Required subscriptions started",String "SubscriptionTrace"]
[db-sync-node:Info:35] [2020-12-20 09:24:20.35 UTC] Database tip is at slot 6952809, block 4612656
[db-sync-node:Info:40] [2020-12-20 09:24:20.35 UTC] Running DB thread
[db-sync-node:Info:40] [2020-12-20 09:24:20.46 UTC] Rolling back to slot 6650000, hash de4298e64c7e784531edee76af7a535599999a08e54726ed8873acc608bf6168
[db-sync-node:Info:44] [2020-12-20 09:24:20.47 UTC] getHistoryInterpreter: acquired
[db-sync-node:Info:40] [2020-12-20 09:24:20.56 UTC] Deleting slots numbered: [6952809..6650009]
```

tip of corresponding producer cardano-node instance::
```
Current tip:
Block hash: bafb2cb6ef88b6c2f41b103bb3f5019fdded0e0268ac5ba1eff33faee0141ba7
Slot: 16897175
Block number: 5101372
```

last db-sync crash: 128m ago (lines up with hitting 4gb memory cap in graph below):

![image](https://user-images.githubusercontent.com/69246342/102714829-66fcaa00-429f-11eb-87f3-60a99a308b14.png)

![image](https://user-images.githubusercontent.com/69246342/102714831-695f0400-429f-11eb-880c-ce93a77872e9.png)

**Comment by erikd** [comment]
You guess at August - November 2020 is almost certainly due to the switch from Byron to Shelley. The first Shelley epoch is number 208. Shelley has a lot more functionality that Byron and that comes at an extra cost of higher CPU and memory consumption. Gougen (coming first quarter next year) is likely to have still higher memory and CPU consumption. When developing `db-sync` I am careful to keep memory to a minimum.

Running `db-sync` in extremely memory constrained environments (ie less that 4GB) is unlikely to work.  Even 4GB of RAM is rather low, I would suggest 8GB as a sensible minimum.

**Comment by erikd** [comment]
I have a PR (https://github.com/input-output-hk/cardano-db-sync/pull/456)  to add a "System Requirements" section to the Readme file.

**Comment by erikd** [comment]
Closing this.
