### ISSUE TITLE
Postgres running on a different host

### ISSUE THREAD

**Issue by mogadget** [input-output-hk/cardano-db-sync#523]
How to set the pgpass value if Postgres is hosted outside of the dbsync host
```
172.12.34.567:5432:dbsync_db:postgress_user:pgpassword
```
This pgpass returns
```
psql: error: fe_sendauth: no password supplied
```

**Comment by mmahut** [comment]
@mogadget this is more of a support question than really an issue related to `cardano-db-sync`.

However, can you please provide more data? What is the `psql` you are using?

**Comment by mogadget** [comment]
Thanks, @mmahut Im using postgresql-client on ubuntu 20.04.  The error appears when running db-sync
```
PGPASSFILE=config/pgpass db-sync-node/bin/cardano-db-sync-extended --config config/mainnet-config.yaml
```

**Comment by erikd** [comment]
This is not a recommended configuration. During syncing (which takes about 6 hours) there is a huge amount of data traffic between `db-sync` and `posgtgres`. Having `postgres` on a different machine (even if it is on the same local network) will cause a significant slowdown in sync speed.

Since it is not a recommended configuration, this is not considered something of high priority.

**Comment by erikd** [comment]
I have added a recommendation to the `Readme.md` file that `db-sync` and the database be run on the same machine.

**Comment by mogadget** [comment]
@erikd Thanks for the info but hopefully provide an option in the future even if there's some latency tradeoff
