### ISSUE TITLE
Cardano node is not syncing

### ISSUE THREAD

**Issue by PrernaPadhee** [input-output-hk/cardano-db-sync#854]
Node sync status is stuck at block 6236059
Postgres service is using alot of CPU
![image](https://user-images.githubusercontent.com/29208607/134498831-07e1f416-6ff2-43c5-a288-caaed29ba759.png)
Following are the logs at the moment 
db-sync
![image](https://user-images.githubusercontent.com/29208607/134498952-018c91a9-170f-4917-9f35-75fce9a88e6d.png)
cardano node 
![image](https://user-images.githubusercontent.com/29208607/134499107-bb77db67-b179-48ea-8f94-71fa8f01a9f7.png)
graphql
![image](https://user-images.githubusercontent.com/29208607/134499213-8b3747a1-2677-4ede-b7c7-b998d673f194.png)

The VM on which the containers are running has 32 CPUs currently

**Comment by erikd** [comment]
The claim is that the node is not syncing. That is definitely not a `db-sync` issue.

The `node` logs do seem to support the claim that the `node` is not connecting to the network but they do not have any further information, not even the current block height.

Since this is seems (from the claims made, and not contradicted by the log messages included) this is a `node` issue, I would recommend closing this and opening a ticket against the `node`, dropping all information about components other than the node. I would also request that logs be included as text (rather than a screenshot) and more logs than what you have above.

**Comment by erikd** [comment]
@PrernaPadhee is this issue sorted out? Can this be closed?
